### ISSUE TITLE
DTA is not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by amirali** [downthemall/downthemall-legacy#272] opened 2017-11-17 17:02 UTC
when this problem will be fix on firefox quantum (57)?

**Comment by Logitech-byte** [comment] 2017-11-18 13:44
Me too, i want this tool is very usefull. Thanks. 💯

**Comment by damoclark** [comment] 2017-11-19 02:47
Nils is [working on a new version right now](https://www.downthemall.net/delays/).  But like many open source developers, Nils' work on dta is unpaid.  

You might consider a [donation](http://www.downthemall.net/howto/donate/) or become a [patron](https://www.patreon.com/nmaier) of Nils' work.

**Comment by mapulse** [comment] 2017-11-21 22:08
sandly end, I can't wait new version. Quantum is sucks.

**Comment by jarredou** [comment] 2017-11-23 11:58
But **UNlike** many open source developers, Nils works alone, instead of working with the community... that's why it's still not here... and that's why it will be full of bugs.

**Comment by EMBBlaster** [comment] 2017-11-24 16:45
Should be closed as duplicate of issue #240.

**Closed as completed** 2017-11-27 10:58 UTC

**Comment by bandaid** [comment] 2017-11-29 13:05
> But **UNlike** many open source developers, Nils works alone, instead of working with the community... that's why it's still not here... and that's why it will be full of bugs.

**Unlike**?! 

Most Open-Source developers work alone. It's how the internet use to work. It is how the internet was born and flourished. Then communities were formed. Then some awesome stuff was made, and awesome communities. BUT... then some capitalist swine got a hold of some Open-Source developers and broke the internet and tried to dismantle and profit from Open-Source. 

You know, if Mozilla hadn't filled Gecko with bloatware (post 3.6)... then it would still be faster than Chromium today even... but noooo we had to get some capitalists into Mozilla and screw it all up with all their uncreative additions (ie: Persona Themes, Pocket, Integrating social media, and more useless bloat) that ought to have stayed at bay as add-ons. ***In very simple terms*** A browsers ONLY function is to provide, securely, access to text based internet. ***IVST***

**Comment by Logitech-byte** [comment] 2017-11-30 18:13
The only thing it sucks is the new Youtube forcing users to stop using Ublock because it pushes to 50% slow in one single page because of the stupid sponsors. Anyways, i can´t wait for the newest version, really need to update a few websites with pictures i need.
