### ISSUE TITLE
When will you support he newest Firefox?

### ISSUE THREAD

**Issue by BionicRooster** [downthemall/downthemall-legacy#295] opened 2018-08-25 11:03 UTC
### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by d7415** [comment] 2018-09-17 16:47
Duplicate of #270

**Comment by nmaier** [comment] 2019-08-20 15:20
Soon: https://github.com/downthemall/downthemall

**Closed as completed by nmaier** 2019-08-20 15:20 UTC
